### ISSUE TITLE
Present to pangeo

### ISSUE THREAD

**Issue by martindurant** [informatics-lab/intake_informaticslab#18]
Would someone be interested in presenting the idea behind this package to the pangeo group, which has similar concerns around intake catalogues of earth/weather data?

**Comment by tam203** [comment]
I'd love to and I'd also invite my colleague @arh89 if he's available. When and where?

**Comment by martindurant** [comment]
~40min from now, see https://pangeo.io/meeting-notes.html for the invite and telecon link

**Comment by tam203** [comment]
Sure I'll make it. It might be a little waffly since I've not prepped.

**Comment by martindurant** [comment]
It's very informal, don't worry. Closing this issue as resolved.

**Comment by tam203** [comment]
"Schedule: Every other Wednesday at 6p GMT" - that's an hour away. have I got my times correct? @martindurant

**Comment by martindurant** [comment]
No, this is the general group meeting, although there is a separate pangeo-forge that this would be suite to also. Starting in 5 - unless my g-calendar is messed up.

Pangeo Community Meeting -- Early Week
When
Wed, January 27, 9am – 10am
Where
https://columbiauniversity.zoom.us/j/953527251 (map)
Description
Meeting notes: https://docs.google.com/document/d/1BkL0arf1Lz6fHgVBEJNxKbFmVN8glNQXmDKdsuT0GcU/edit#
more details»  copy to my calendar

That time is US pacific, I think. If you go to the invite link or the gdoc link above, it has the time 5pm+0000 (GMT)
